version: '3.5'
services:
    dotnetapp:
        image: nandacamargo/dotnet_firstapp
        container_name: dotnet_app
        build:
            context: ./FirstApp.API
            dockerfile: dotnet.dockerfile
        volumes:
            - ./FirstApp.API:/first_app
        ports:
            - "5000:80"
        networks:
            - mynetwork
    
    angularapp:
        image: nandacamargo/angular_firstapp
        container_name: angular_app
        build:
            context: ./FirstApp-SPA
            dockerfile: angular.dockerfile
        volumes:
            - ./FirstApp-SPA:/usr/src/app
        ports:
            - "4200:4200"
        networks:
            - mynetwork
        depends_on:
            - dotnetapp



networks:
    mynetwork:
       driver: bridge


